### ISSUE TITLE
Compatibility with GoldSRC DLLs

### ISSUE THREAD

**Issue by HamletEagle** [asherkin/vtable#1]
I've tried the tool with "cs.so"(Counter Strike 1.6 mod dll) and the result was:
`
0	0	(pure virtual function)
`

Also a warning was displayed
`Some Windows Indexes May Be Incorrect
This class uses C++ features which can not be accounted for by this tool.`

**Comment by asherkin** [comment]
This is quite a crazy amount of work, need to implement full relocation handling.

**Comment by asherkin** [comment]
The relocations are in the `.rel.dyn` section, and at least all the vtable symbols are simple R_386_32 ones - don't know atm if the function addresses are going to need handling as well to match them up with the symbols.

**Comment by asherkin** [comment]
Well this was indeed an insane amount of work.

Thanks for the report, this is now fixed and should be deployed on the live site within a few minutes.
