### ISSUE TITLE
It doesn't do anything...

### ISSUE THREAD

**Issue by MAGNAT2645** [asherkin/vtable#4]
I tried download .so from Dumper and used my own server_srv.so but nothing happens, just says "Processing...".
Maybe this due to browser bug or something on Dumper side.

**Comment by asherkin** [comment]
From [the thread](https://forums.alliedmods.net/showthread.php?t=281859
):
> As a heads up, this is currently broken in Chrome 57+ for large binaries (such as TF2's server bin) until I have time to rewrite how the WebWorker passes the processing results back - the Chrome team made a change that massively increases performance in the general case, but reduces the depth limit for serializing objects.

**Comment by MAGNAT2645** [comment]
Ok, thanks for quick response.
I think i can close this issue.
