### ISSUE TITLE
Issue with latest tf2 server binary file

### ISSUE THREAD

**Issue by Kenzzer** [asherkin/vtable#5]
`Failed to demangle '_ZN16CFuncRespawnR' (input is not a valid name under the C++ ABI mangling rules)`

Constructor & Destruction will be dumped fine, but not the rest of virtual functions.

**Comment by asherkin** [comment]
The current TF2 server binary on the server the site uses for the quick buttons is corrupt, drag-and-drop a local copy of `server_srv.so` to the site and it should work fine. This'll resolve itself with the next TF2 update (or possibly sooner.)

**Comment by Kenzzer** [comment]
Thanks!
